namespace: m4eba
name: kubernetes
version: 0.1.2
readme: README.md
authors:
  - m4eba
description: An ansible collection for kuberentes cluster with kubeadm.
license_file: 'LICENSE'
tags: []
dependencies:
  community.general: '>=4.2.0'
  kubernetes.core: '>=2.2.2'
repository: http://github.com/m4eba/ansible-kubernetes
issues: http://github.com/m4eba/ansible-kubernetes/issues
