---
- name: Check if kubeadm has already run
  stat:
    path: '/etc/kubernetes/pki/{{ file }}'
  register: kubeadm_ca
- name: Set var kubeadm_exists
  set_fact: kubeadm_exists={{ kubeadm_ca.stat.exists }}
- name: Set need token
  set_fact:
    need_token: true
  delegate_to: localhost
  delegate_facts: true
  when: not kubeadm_exists
