---
- name: Create secret with hcloud token
  ansible.builtin.command: kubectl -n kube-system create secret generic hcloud --from-literal=token={{ hcloud_token }}
  when: not hcloud_with_networks
- name: apply hcloud ccm
  ansible.builtin.command: kubectl apply -f  https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v{{ hcloud_controller_manager_version }}/ccm.yaml
  when: not hcloud_with_networks
- name: Create secret with hcloud token
  ansible.builtin.command: kubectl -n kube-system create secret generic hcloud --from-literal=token={{ hcloud_token }} --from-literal=network={{ hcloud_network_name }}
  when: hcloud_with_networks
- name: apply hcloud ccm
  ansible.builtin.command: kubectl apply -f  https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v{{ hcloud_controller_manager_version }}/ccm-networks.yaml
  when: hcloud_with_networks
- name: Create secret with hcloud token
  ansible.builtin.command: kubectl -n kube-system create secret generic hcloud-csi --from-literal=token={{ hcloud_token }}
  register: command_result
  changed_when: command_result.rc == 0
- name: apply hcloud csi
  ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v{{ hcloud_csi_driver_version }}/deploy/kubernetes/hcloud-csi.yml
  register: command_result
  changed_when: command_result.rc == 0