---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: controller1
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.50.11'"
    groups:
      - etcd
      - controller
  - name: controller2
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'private_network', ip: '192.168.50.12'"
    groups:
      - etcd
      - controller
provisioner:
  name: ansible
verifier:
  name: ansible
